In [1]:
import pandas as pd
import os
import glob
from time import sleep
from tqdm import tqdm
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import re

## First, concatenate all CSVs

In [21]:
# path1 = "Data/" # might not apply if this file is also in the same file location as the collection of CSVs
# path1_files = glob.glob(os.path.join(path1, ".csv"))
# joined_df = pd.concat((pd.read_csv(f) for f in path1_files)).drop_duplicates().reset_index(drop=True)
# joined_df.to_csv('Data/allFulton.csv')
# print("export complete!")

In [5]:
df = pd.read_csv('Data/data_clean.csv')

df.head()

,id,Address,County,State,Sale Date,Sale Year,Sale Month,Sale Price,lat,long,block
0,989,1112 MOORES MILL RD NW,Fulton County,Georgia,1/3/17,2017,Jan,1325000,33.835352,-84.423451,1.312100e+11
1,1061,3324 PEACHTREE RD NE,Fulton County,Georgia,1/3/17,2017,Jan,215500,33.845768,-84.369424,1.312100e+11
2,1390,497 KING RD NW,Fulton County,Georgia,1/3/17,2017,Jan,4362991,33.863542,-84.402923,1.312100e+11
3,1725,2620 PINEY WOOD TER,Fulton County,Georgia,1/3/17,2017,Jan,157500,33.684522,-84.478954,1.312100e+11
4,2150,9 IVY TRL NE,Fulton County,Georgia,1/3/17,2017,Jan,260000,33.857606,-84.380292,1.312100e+11